networks:
  NetworkService:
    driver: bridge
    name: Inception-net

services:

  server:
    build:
      context: .
      dockerfile: dockerfile.server 
    networks:
      - NetworkService
    image: apppartthree:V2
    container_name: apppartthreeAbaitta
    volumes:
      - ./:/server
    restart: always