# -*- mode: ruby -*-
# vi: set ft=ruby :

MEMORY_CAPACITY = 1024

RECOMMENDED_CPU = 1
CONTROLLER_IP = "192.168.56.110"

Vagrant.configure("2") do |config|

  config.vm.define "abait-taS", primary: true do |primary|
    primary.vm.box = "bento/debian-13.0"
    primary.vm.hostname = "abait-taS"

    primary.vm.provider "virtualBox" do |provider|
      provider.name = "abait-taS"
      provider.cpus = RECOMMENDED_CPU
      provider.memory = MEMORY_CAPACITY
    end

    primary.vm.network "private_network", ip: CONTROLLER_IP
    primary.vm.provision :shell, name: "server_provision", path: "./scripts/server_provision.sh", args: [CONTROLLER_IP]
  end

end